entries/forms.py
import wtforms
from wtforms.validators import DataRequired


from models import Entry, Tag


class TagField(wtforms.StringField):
    def _value(self):
        if self.data:
            # Display tags as a comma-separated list.
            return ', '.join([tag.name for tag in self.data])
        return ''
    
    def get_tags_from_string(self, tag_string):
        raw_tags = tag_string.split(',')
        
        #Filter out any empty tag name.
        tag_names = [name.strip() for name in raw_tags if name.strip]
        
        # Query the database and retrieve any tags we have already saved
        existing_tags = Tag.query.filter(Tag.name.in_(tag_names))
        
        # Determine which tag names are new
        new_names = set(tag_names) - set([tag.name for tag in existing_tags])
        
        # Create a list of unsaved Tag instances for the new tags.
        new_tags = [Tag(name=name) for name in new_names]
        
        # Return all the existing tags + all the new, unsaved tags.
        return list(existing_tags) + new_tags
    
    
    def process_formdata(self, valuelist):
        if valuelist:
            self.data = self.get_tags_from_string(valuelist[0])
        else:
            self.data = []


class EntryForm(wtforms.Form):
    title = wtforms.StringField('Title', validators=[DataRequired()])
    body = wtforms.TextAreaField('Body', validators=[DataRequired()])
    status = wtforms.SelectField(
        'Entry Status',
        choices= (
            (Entry.STATUS_PUBLIC, 'Public'),
            (Entry.STATUS_DRAFT, 'Draft')),
        coerce=int
    )
    tags = TagField(
        'Tags', description='Separate multiple tags with commas.'
    )
    
    
    def save_entry(self, entry):
        self.populate_obj(entry)
        entry.generate_slug()
        return entry
    
    
class ImageForm(wtforms.Form):
    file = wtforms.FileField('Image file')

entries/blueprint.py
import os

from flask import Blueprint, render_template, request, redirect, url_for, flash, g
from werkzeug import secure_filename
from flask_login import login_required

from models import Entry, Tag
from helpers import object_list
from entries.forms import EntryForm, ImageForm
from app import app, db


entries = Blueprint('entries', __name__, template_folder='templates')

@entries.route("/")
def index():
    entries = Entry.query.order_by(Entry.created_timestamp.desc())
    return entry_list('entries/index.html', entries)



@entries.route("/tags/")
def tag_index():
    tags = Tag.query.order_by(Tag.name)
    return object_list('entries/tag_index.html', tags)


@entries.route("/tags/<slug>")
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    entries = tag.entries.order_by(Entry.created_timestamp.desc())
    return object_list('entries/tag_detail.html', entries, tag=tag)




@entries.route('/create/', methods=['GET', 'POST'])
@login_required
def create():
    if request.method == 'POST':
        form = EntryForm(request.form)
        if form.validate():
            entry = form.save_entry(Entry(author=g.user))
            db.session.add(entry)
            db.session.commit()
            flash("Entry '%s' created succesfully." % entry.title, 'success')
            return redirect(url_for('entries.detail', slug=entry.slug))
    else:
        form = EntryForm()
    return render_template('entries/create.html', form=form)


@entries.route("/image-upload/", methods=['GET', 'POST'])
@login_required
def image_upload():
    if request.method == 'POST':
        form = ImageForm(request.form)
        if form.validate():
            image_file = request.files['file']
            filename = os.path.join(app.config['IMAGES_DIR'],
                        secure_filename(image_file.filename)
            )
            image_file.save(filename)
            flash("Saved %s" % os.path.basename(filename), 'success')
            return redirect(url_for('entries.index'))
    else:
        form = ImageForm()
    return render_template('entries/image_upload.html', form=form)

@entries.route("/<slug>/")
def detail(slug):
    #entry = Entry.query.filter(Entry.slug == slug).first_or_404()
    entry = get_entry_or_404(slug)
    return render_template('entries/detail.html', entry=entry)



@entries.route("/<slug>/edit/", methods=['GET', 'POST'])
@login_required
def edit(slug):
    #entry = Entry.query.filter(Entry.slug == slug).first_or_404()
    entry = get_entry_or_404(slug, author=None)
    if request.method == 'POST':
        form = EntryForm(request.form, obj = entry)
        if form.validate():
            entry = form.save_entry(entry)
            db.session.add(entry)
            db.session.commit()
            flash("Entry '%s' has been saved." % entry.title, 'success')
            return redirect(url_for('entries.detail', slug=entry.slug))
    else:
        form = EntryForm(obj=entry)
    return render_template('entries/edit.html', entry=entry, form=form)
    
        


@entries.route('/<slug>/delete/', methods=['GET', 'POST'])
@login_required
def delete(slug):
    #entry = Entry.query.filter(Entry.slug == slug).first_or_404()
    entry = get_entry_or_404(slug, author=None)
    if request.method == 'POST':
        entry.status = Entry.STATUS_DELETED
        db.session.add(entry)
        db.session.commit()
        flash("Entry '%s' has been deleted succesfully." % entry.title, 'success')
        return redirect(url_for('entries.index'))
    return render_template('entries/delete.html', entry=entry)




def entry_list(template, query, **context):
    query = filter_status_by_user(query)
    valid_statuses = (Entry.STATUS_DRAFT, Entry.STATUS_PUBLIC)
    query = query.filter(Entry.status.in_(valid_statuses))
    if request.args.get('q'):
        search = request.args['q']
        query = query.filter(
            (Entry.body.contains(search)) |
            (Entry.title.contains(search))
        )
    return object_list(template, query, **context)


def get_entry_or_404(slug, author=None):
    query = Entry.query.filter(Entry.slug == slug)
    if author:
        query = query.filter(Entry.author == author)
    else:
        query = filter_status_by_user(query)
    return query.first_or_404()

def filter_status_by_user(query):
    if not g.user.is_authenticated:
        query = query.filter(Entry.status == Entry.STATUS_PUBLIC)
    else:
        # Allow user to view thier own drafts.
        query = query.filter(
            (Entry.status == Entry.STATUS_PUBLIC) |
            ((Entry.author == g.user) &
            (Entry.status != Entry.STATUS_DELETED))
        )
    return query

entries/templates/entries/base_entries.html
{% extends "base.html" %}

{% block sidebar %}
	<form class="form-inline well" method="get" role="form">
		<div class="input-group">
			<input class="form-control input-xs" name="q"
			     placeholder="Search..." value="{{ request.args.get('q', '') }}" />
			<span class="input-group-btn">
			<button class="btn btn-default" type="submit">Go</button>
			</span>
		</div>
	</form>
{% endblock %}
{% block content %}
    {% include "includes/list.html" %}
    {% include "includes/page_links.html" %}
{% endblock %}

entries/templates/entries/create.html
{% extends "base.html" %}
{% from "macros/form_field.html" import form_field %}
{% block title %}Create new entry{% endblock %}
{% block content_title %}Create new entry{% endblock %}
{% block content %}
	<form action="{{ url_for('entries.create') }}" class="form form-horizontal" method="post">
		{% for field in form %}
		  {{ form_field(field) }}
        {% endfor %}
		<div class="form-group">
			<div class="col-sm-offset-3 col-sm-9">
			    <button type="submit" class="btn btn-default">Create</button>
			    <a class="btn" href="{{ url_for('entries.index') }}">Cancel</a>
			</div>
		</div>
	</form>
{% endblock %}

entries/templates/entries/delete.html
{% extends "base.html" %}
{% block title %}{{ entry.title }}{% endblock %}
{% block content_title %}{{ entry.title }}{% endblock %}
{% block content %}
<form action="{{ url_for('entries.delete', slug=entry.slug) }}" method="post">
	<fieldset>
		<legend>Delete this entry?</legend>
		<button class="btn btn-danger" type="submit">Delete</button>
		<a class="btn" href="{{ url_for('entries.detail', slug=entry.slug) }}">Cancel</a>
	</fieldset>
</form>
{% endblock %}

entries/templates/entries/detail.html
{% extends "base.html" %}

{% block title %}{{ entry.title }}{% endblock %}

{% block content_title %}{{ entry.title }}{% endblock %}

{% block sidebar %}
<ul class="well nav nav-list">
	<li><h4>Tags</h4></li>
	{% for tag in entry.tags %}
	<li>
	   <a href="{{ url_for('entries.tag_detail', slug=tag.slug) }}">{{ tag.name }}</a>
	</li>
	{% endfor %}
	{% if g.user == entry.author %}
		<li><h4>Actions</h4></li>
		<li><a href="{{ url_for('entries.edit', slug=entry.slug) }}">Edit</a></li>
		<li><a href="{{ url_for('entries.delete', slug=entry.slug) }}">Delete</a></li>
	{% endif %}
</ul>
<p>Published {{ entry.created_timestamp.strftime('%m/%d/%Y')}}</p>
{% endblock %}
{% block content %}
    {{ entry.body }}
{% endblock %}

entries/templates/entries/edit.html
{% extends "base.html" %}

{% from "macros/form_field.html" import form_field %}

{% block title %}Edit {{ entry.title }}{% endblock %}

{% block content_title %}Edit {{ entry.title }}{% endblock %}

{% block content %}

<form action="{{ url_for('entries.edit', slug=entry.slug) }}" class="form form-horizontal" method="post">
	{% for field in form %}
	   {{ form_field(field) }}
	{% endfor %}
	<div class="form-group">
		<div class="col-sm-offset-3 col-sm-9">
			<button type="submit" class="btn btn-default">Save</button>
			<a class="btn" href="{{ url_for('entries.detail', slug=entry.slug) }}">Cancel</a>
		</div>
	</div>
</form>
{% endblock %}

entries/templates/entries/image_upload.html
{% extends "base.html" %}
{% from "macros/form_field.html" import form_field %}
{% block title %}Upload an image{% endblock %}
{% block content_title %}Upload an image{% endblock %}
{% block content %}
  <form action="{{ url_for('entries.image_upload') }}" enctype="multipart/form-data" method="post">
    {% for field in form %}
      {{ form_field(field) }}
    {% endfor %}
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-9">
        <button type="submit" class="btn btn-default">Upload</button>
        <a class="btn" href="{{ url_for('entries.index') }}">Cancel</a>
      </div>
    </div>
  </form>
{% endblock %}

entries/templates/entries/index.html
{% extends "entries/base_entries.html" %}

{% block title %}Entries{% endblock %}

{% block content_title %}Entries{% endblock %}

{% block content %}
    {% include "includes/list.html" %}
    {% include "includes/page_links.html" %}
{% endblock %}

entries/templates/entries/tag_detail.html
{% extends "entries/base_entries.html" %}

{% block title %}{{ tag.name }} entries{% endblock %}

{% block content_title %}{{ tag.name }} entries{% endblock %}

{% block content %}
    {% include "includes/list.html" %}
{% endblock %}

entries/templates/entries/tag_index.html
{% extends "base.html" %}

{% block title %}Tags{% endblock %}

{% block content_title %}Tags{% endblock %}
{% block content %}
	<ul>
	{% for tag in object_list.items %}
	<li><a href="{{ url_for('entries.tag_detail', slug=tag.slug) }}">{{ tag.name }}</a></li>
	{% endfor %}
	</ul>
	{% include "includes/page_links.html" %}
{% endblock %}